/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stock_market_Crawler */

#ifndef _Included_stock_market_Crawler
#define _Included_stock_market_Crawler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stock_market_Crawler
 * Method:    getJSON
 * Signature: (Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stock_1market_Crawler_getJSON
  (JNIEnv *, jobject, jstring, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
